# Generated by Django 4.1.3 on 2022-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer_Name', models.CharField(default=None, max_length=50)),
                ('job_seeker_Name', models.CharField(default=None, max_length=50)),
                ('Employer_Id', models.CharField(default=None, max_length=50)),
                ('job_seeker_Id', models.CharField(default=None, max_length=50)),
                ('catagory', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
