# Generated by Django 4.1.3 on 2022-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
