# Generated by Django 4.1.3 on 2022-11-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_apply_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
