# Generated by Django 4.1.3 on 2022-11-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
